# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]	
	
#7 segment display
set_property PACKAGE_PIN W7 [get_ports {display[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[7]}]
set_property PACKAGE_PIN W6 [get_ports {display[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]
set_property PACKAGE_PIN U8 [get_ports {display[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property PACKAGE_PIN V8 [get_ports {display[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property PACKAGE_PIN U5 [get_ports {display[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property PACKAGE_PIN V5 [get_ports {display[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property PACKAGE_PIN U7 [get_ports {display[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property PACKAGE_PIN V7 [get_ports {display[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]

#set_property PACKAGE_PIN V7 [get_ports dp]							
	#set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {digit[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[0]}]
set_property PACKAGE_PIN U4 [get_ports {digit[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[1]}]
set_property PACKAGE_PIN V4 [get_ports {digit[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[2]}]
set_property PACKAGE_PIN W4 [get_ports {digit[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {digit[3]}]

#LED
set_property PACKAGE_PIN L1 [get_ports {LED[0]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN P1 [get_ports {LED[1]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN N3 [get_ports {LED[2]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN P3 [get_ports {LED[3]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]

#Buttons
set_property PACKAGE_PIN T18 [get_ports rst_n]						
	set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN W19 [get_ports insert_5]						
	set_property IOSTANDARD LVCMOS33 [get_ports insert_5]
set_property PACKAGE_PIN U18 [get_ports insert_10]						
	set_property IOSTANDARD LVCMOS33 [get_ports insert_10]
set_property PACKAGE_PIN T17 [get_ports insert_50]						
	set_property IOSTANDARD LVCMOS33 [get_ports insert_50]
set_property PACKAGE_PIN U17 [get_ports cancel]						
	set_property IOSTANDARD LVCMOS33 [get_ports cancel]
 
#USB HID (PS/2)
set_property PACKAGE_PIN C17 [get_ports PS2_CLK]						
	set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
	set_property PULLUP true [get_ports PS2_CLK]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]					
	set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]	
	set_property PULLUP true [get_ports PS2_DATA]

